num1 = int(input("give number1:"))
num2 = int(input("give number2:"))
print("resultat:",num1 + num2)
print("resultat:",num1 - num2)
print("resultat:",num1 * num2)
print("resultat:",num1 / num2)
print("resultat:",num1 // num2)
print("resultat:",num1 ** num2)
print("resultat:",num1 % num2)
